SmartDashboard buttons
FRC701/ragnorok pull request #12
Opened 2017-01-19 00:06 UTC by MajorDarius

Included the new commands to OI and added buttons for the SmartDashboard for the new commands

2017-01-19 02:40 UTC, duane701 requested changes
FTP

2017-01-19 02:40 UTC, duane701 commented on src/OI.cpp
> +  SmartDashboard::PutData("TurretOn", new SetTurret(1.0));
How do we turn them off?

2017-01-19 02:40 UTC, duane701 commented on src/OI.cpp
> +  SmartDashboard::PutData("FeederOn", new ConveyorControl(1.0, 0.0));
The string "FeederOn" in this case is used in the SmartDashboard user interface as a title for the control. I think you can actually have spaces and use real English and capitalization and everything. 😈 

Perhaps "Feeder On", "Mover On"? or is that just weird?

2017-01-19 21:46 UTC, Diego-Andrade commented on src/OI.cpp
> +  SmartDashboard::PutData("TurretOn", new SetTurret(1.0));
You cancel the command on the Smart Dashboard. If you haven't seen the buttons, they initially have a Start button next to them, and once click it transforms to a Cancel.

2017-01-19 22:33 UTC, duane701 commented on src/OI.cpp
> +  SmartDashboard::PutData("TurretOn", new SetTurret(1.0));
Thanks @Diego-Andrade. 

Walking through the process ... 

1. Press Start. The command starts running on this Talon. The button changes to Cancel.
2. Press Cancel.
  a. The current command is interrupted and exits.
  b. The default command is instantiated and restarted.

But wait ... most of these subsystems have no default command. Due to the implementation of the Talon, the previous setting keeps running. 

I think we should have taken your (@Diego-Andrade) early suggestion to write default commands for all of these systems. 

Do we have default commands for each of these subsystems that disables the talons (ie set the motor to 0?).

2017-01-19 22:44 UTC, duane701 commented
Thank you for the fixup commit. However, fixup is specifically spelled `fixup!`. No mixed case. So close. 😜

2017-01-20 05:36 UTC, duane701 commented
LGTM.

I checked the subsystems referenced here all have default commands. `Lifter` is the only subsystem missing a default command. We can fix that in future work when we know more about the lifter.

I will handle the rebase and push a new branch. If someone else can do the PR, I can approve it.

2017-01-20 05:38 UTC, duane701 commented
See new branch `feature/SmartDashBoard.v1`

2017-01-20 05:38 UTC, closed without merging