RFC: An idea for Nudge (DO NOT MERGE)
FRC701/ragnorok pull request #30
Opened 2017-02-04 18:12 UTC by duane701

This one doesn't seem to work because commands
must be managed. The scheduler does not manage commands.

Commands are owned and managed by the buttons. (They are never deleted.)

DO NOT MERGE

2017-02-04 19:08 UTC, duane701 commented
Closing for a new branch.

2017-02-04 22:52 UTC, SkylerPIlot requested changes

2017-02-04 22:52 UTC, SkylerPIlot commented on src/Commands/NudgeShooter.h
> +  double mNudge;
Make this a private variable `private:`

2017-02-04 22:52 UTC, SkylerPIlot commented on src/Commands/SetShooter.cpp
Get rid of this whitespace

2017-02-04 22:52 UTC, SkylerPIlot commented on src/Commands/SetShooter.h
>  	double mSpeed;
fix tabing here

2017-02-04 22:52 UTC, SkylerPIlot commented on src/Commands/SetShooter.h
> +  double GetSpeed() const;
follow the example of how functions are organized

2017-02-05 00:40 UTC, duane701 commented on src/Commands/SetShooter.h
> +  double GetSpeed() const;
Functions should be organized alphabetically or  as in this case, by related functionality. That is the Getter and the Setter are next to each other.

Also, whitespace is great but we don't have to use every other line.

2017-02-05 18:32 UTC, duane701 commented
Closed in favor of #31

2017-02-05 18:32 UTC, closed without merging