Fixed white space and placement style problems.
FRC701/ragnorok pull request #58
Opened 2017-03-03 23:26 UTC by OliviaRS

2017-03-04 17:07 UTC, MajorDarius commented on src/Commands/AutonomousCommand.h
>   */
This comment doesn't have a partner, do we need it?

2017-03-04 17:12 UTC, MajorDarius commented on src/Commands/AutonomousCommand.h
>   */
Do we need this comment? If not we should get rid of it.

2017-03-04 17:13 UTC, MajorDarius commented on src/Commands/TankDrive.h
>   */
Same thing as the other one, do we need this comment?

2017-03-04 17:17 UTC, MajorDarius requested changes
Check out comments but everything else looks good

2017-03-05 18:32 UTC, duane701 requested changes
FTP

2017-03-05 18:32 UTC, duane701 commented on src/Commands/AutonomousCommand.h
>   */
@MajorDarius, are you referring to the end of comment shown in the diff view or the entire comment shown in the file?

Remember that the diff view does not show the entire file. Only the changes to the file are shown in the diff view. 

However, looking at the file, I'm not sure that the comment actually has any value. But we don't need to change it for this PR.

2017-03-05 18:32 UTC, duane701 commented on src/OI.cpp
> +  static const double kPositionNudge = 0;
Double and float should always include a decimal point. This is technically assigning an integer to a double. The integer is promoted to a double. If the number includes the decimal point, then a double is assigned to a double, not conversion is required.

2017-03-05 18:32 UTC, duane701 commented on src/Robot.cpp
> +  SmartDashboard::PutNumber("Lifter OutPut Voltage", Lifter::getInstance()->GetCurrent());
"OutPut" should be "Output", and this appears to be mislabeled. The function is called `GetCurrent()`.

2017-03-15 21:39 UTC, MajorDarius approved these changes
LGTM

2017-07-25 22:07 UTC, duane701 commented
Outdated. Redone in a later PR.

2017-07-25 22:07 UTC, closed without merging